<?php

namespace GSPEM\GSPEMBundle\Repository;

/**
 * MaterialTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterialTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
