<?php

namespace GSPEM\GSPEMBundle\Repository;

/**
 * MovStockSitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovStockSitRepository extends \Doctrine\ORM\EntityRepository
{
}
