<?php

namespace GSPEM\GSPEMBundle\Repository;

/**
 * MovStockTecRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovStockTecRepository extends \Doctrine\ORM\EntityRepository
{
}
