<?php

namespace GSPEM\GSPEMBundle\Repository;

/**
 * PerfilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerfilesRepository extends \Doctrine\ORM\EntityRepository
{
}
