<?php

namespace GSPEM\GSPEMBundle\Repository;

/**
 * SitioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SitioRepository extends \Doctrine\ORM\EntityRepository
{
}
