<?php

namespace GSPEM\GSPEMBundle\Repository;

/**
 * SitioTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SitioTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
