<?php

namespace GSPEM\GSPEMBundle\Repository;

/**
 * SockItemsMovRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SockItemsMovRepository extends \Doctrine\ORM\EntityRepository
{
}
