<?php

namespace GSPEM\GSPEMBundle\Repository;

/**
 * StockTecnicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockTecnicoRepository extends \Doctrine\ORM\EntityRepository
{
}
