<?php

namespace GSPEM\GSPEMBundle\Repository;

/**
 * StockSitioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockSitioRepository extends \Doctrine\ORM\EntityRepository
{
}
