<?php

namespace GSPEM\GSPEMBundle\Repository;

/**
 * StockMaestroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockMaestroRepository extends \Doctrine\ORM\EntityRepository
{
}
